// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_ido
    (
        init => init
        upgrade => upgrade
        contribute => contribute
        claimTokens => claim_tokens
        refund => refund
        depositTokens => deposit_tokens
        finalizeIdo => finalize_ido
        withdrawFunds => withdraw_funds
        withdrawUnsoldTokens => withdraw_unsold_tokens
        emergencyCancel => emergency_cancel
        updateTiming => update_timing
        getContribution => get_contribution
        getIdoStatus => get_ido_status
        getIdoInfo => get_ido_info
        getTotalRaised => get_total_raised
        getTotalParticipants => get_total_participants
        getTimeRemaining => get_time_remaining
        getRemainingAllocation => get_remaining_allocation
        getTokensDeposited => get_tokens_deposited
        isSoftCapReached => is_soft_cap_reached
        isHardCapReached => is_hard_cap_reached
        calculateTokensForEgld => calculate_tokens_for_egld
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
