// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    circle_peripheral
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        receive => receive
        transfer => transfer
        forceTransferToSC0 => force_transfer_to_sc0
        signAndForward => sign_and_forward
        deactivate => deactivate
        activate => activate
        getOwner => get_owner
        getSC0Address => get_sc0_address
        isActive => get_is_active
        getBalance => get_balance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
