// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                          112
// Async Callback (empty):               1
// Total number of exported functions: 115

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    circle_of_life_center
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        setPeripheralTemplate => set_peripheral_template
        changeOwner => change_owner
        pause => pause
        unpause => unpause
        setEntryFee => set_entry_fee
        setCirculationAmount => set_circulation_amount
        setDistributionEnabled => set_distribution_enabled
        setDaoContract => set_dao_contract
        setXExchangePair => set_xexchange_pair
        setWegldContract => set_wegld_contract
        setLpLocker => set_lp_locker
        setSlippageTolerance => set_slippage_tolerance
        withdrawPendingLiquidity => withdraw_pending_liquidity
        distributeExistingEgld => distribute_existing_egld
        setRewardToken => set_reward_token
        setRewardPerCycle => set_reward_per_cycle
        depositRewards => deposit_rewards
        withdrawRewards => withdraw_rewards
        setBurnPerSc => set_burn_per_sc
        setStarterBonusPercentage => set_starter_bonus_percentage
        setNftContract => set_nft_contract
        resetCycle => reset_cycle
        initializePioneerIndices => initialize_pioneer_indices
        simulateNextDay => simulate_next_day
        failCycle => fail_cycle
        withdraw => withdraw
        recoverFundsFromPeripheral => recover_funds_from_peripheral
        joinCircle => join_circle
        startDailyCycle => start_daily_cycle
        preSign => pre_sign
        enableAutoSign => enable_auto_sign
        enableAutoSignForCycles => enable_auto_sign_for_cycles
        disableAutoSign => disable_auto_sign
        processNextTransfer => process_next_transfer
        processAllPendingTransfers => process_all_pending_transfers
        signAndForward => sign_and_forward
        setInactive => set_inactive
        setActive => set_active
        leaveCircle => leave_circle
        claimRewards => claim_rewards
        getCircleInfo => get_circle_info
        getMyContract => get_my_contract
        isMember => is_member
        isActive => is_active
        isMyTurn => is_my_turn
        getActiveContracts => get_active_contracts_view
        getAllContracts => get_all_contracts
        getPeripheralTemplate => get_peripheral_template
        getOwner => get_owner
        isPaused => get_is_paused
        getContractBalance => get_contract_balance
        getCycleHolder => get_cycle_holder
        getCycleDay => get_cycle_day
        getCurrentDay => get_current_day_view
        getCycleEpoch => get_cycle_epoch
        getCyclesCompleted => get_cycles_completed
        getCyclesFailed => get_cycles_failed
        getCycleStats => get_cycle_stats
        hasPreSigned => has_pre_signed
        hasSignedThisCycle => has_signed_this_cycle
        getAutoSignStatus => get_auto_sign_status
        isAutoSignEnabled => is_auto_sign_enabled
        getAutoSignUntil => get_auto_sign_until
        getAutoSignRemainingCycles => get_auto_sign_remaining_cycles
        getContractOwner => get_contract_owner
        getAllContractsWithOwners => get_all_contracts_with_owners
        getPreSignedMembers => get_pre_signed_members
        getScStats => get_sc_stats
        getInfractionInfo => get_infraction_info
        willInfractionReset => will_infraction_reset
        isBanned => is_banned
        getAllScStats => get_all_sc_stats
        getRewardTokenId => get_reward_token_id
        getRewardsPool => get_rewards_pool
        getRewardPerCycle => get_reward_per_cycle
        getBaseRewardConfig => get_base_reward_config
        getPendingRewards => get_pending_rewards
        getTotalRewardsDistributed => get_total_rewards_distributed
        getRewardsInfo => get_rewards_info
        isSunday => is_sunday_view
        getDayOfWeek => get_day_of_week
        canClaimRewards => can_claim_rewards
        getCurrentCycleReward => get_current_cycle_reward
        getCurrentEra => get_current_era_view
        getNextCircleCompleteCycle => get_next_circle_complete_cycle
        getCyclesUntilNextHalving => get_cycles_until_next_halving
        getOptionFInfo => get_option_f_info
        isNextCycleCircleComplete => is_next_cycle_circle_complete
        getRewardSchedule => get_reward_schedule
        getTotalBurned => get_total_burned
        getBurnPerSc => get_burn_per_sc
        getBurnStats => get_burn_stats
        getTotalDistributedTreasury => get_total_distributed_treasury
        getTotalDistributedDao => get_total_distributed_dao
        getPendingLiquidityEgld => get_pending_liquidity_egld
        isDistributionEnabled => is_distribution_enabled
        getStarterBonusInfo => get_starter_bonus_info
        getStarterBonusPercentage => get_starter_bonus_percentage
        getCycleStarter => get_cycle_starter
        getTotalStarterBonusDistributed => get_total_starter_bonus_distributed
        getNftContract => get_nft_contract
        isPioneer => is_pioneer
        getPeripheralIndex => get_peripheral_index
        getPioneerInfo => get_pioneer_info
        getRemainingPioneerSlots => get_remaining_pioneer_slots
        getDepositBonusInfo => get_deposit_bonus_info
        getMemberEgldDeposits => get_member_egld_deposits
        getDepositBonusPercent => get_deposit_bonus_percent
        getTotalEgldDeposits => get_total_egld_deposits
        getAllBonuses => get_all_bonuses
        getPendingAutoTransfers => get_pending_auto_transfers
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
