// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           18
// Async Callback (empty):               1
// Total number of exported functions:  21

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    circle_manager
    (
        init => init
        upgrade => upgrade
        createCircle => create_circle
        requestMembership => request_membership
        voteForMember => vote_for_member
        contribute => contribute
        forceDistribute => force_distribute
        distributeFunds => distribute_funds
        getCircle => get_circle
        getCircleCount => get_circle_count
        getCircleMembers => get_circle_members
        isMember => is_member
        getTreasuryBalance => get_treasury_balance
        getPendingRequests => get_pending_requests
        getCircleCreator => get_circle_creator
        hasPendingRequest => has_pending_request_view
        hasVoted => has_voted
        hasContributed => has_contributed_view
        getCycleContributors => get_cycle_contributors
        getCycleContributorCount => get_cycle_contributor_count
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
