// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_vesting
    (
        init => init
        upgrade => upgrade
        depositTokens => deposit_tokens
        createTeamVesting => create_team_vesting
        createAdvisorVesting => create_advisor_vesting
        createMarketingVesting => create_marketing_vesting
        createCustomVesting => create_custom_vesting
        revokeVesting => revoke_vesting
        release => release
        releaseAll => release_all
        getVestingSchedule => get_vesting_schedule
        getReleasableAmount => get_releasable_amount
        getVestedAmount => get_vested_amount
        getBeneficiarySchedules => get_beneficiary_schedules
        getTotalVested => get_total_vested
        getTotalReleased => get_total_released
        getTimeUntilCliffEnd => get_time_until_cliff_end
        getTimeUntilFullyVested => get_time_until_fully_vested
        getTokenId => get_token_id
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
