// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           24
// Async Callback:                       1
// Total number of exported functions:  27

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_nft
    (
        init => init
        upgrade => upgrade
        issueCollection => issue_collection
        setLocalRoles => set_local_roles
        addUriRole => add_uri_role
        setCircleOfLifeContract => set_circle_of_life_contract
        setBaseUri => set_base_uri
        setLevelUri => set_level_uri
        setAllLevelUris => set_all_level_uris
        setRoyaltiesAddress => set_royalties_address
        claimNft => claim_nft
        mintForMember => mint_for_member
        burnAndReclaim => burn_and_reclaim
        evolveNft => evolve_nft
        checkEvolution => check_evolution
        updateMemberCycles => update_member_cycles
        getNftInfo => get_nft_info
        hasNft => has_nft
        getNftLevel => get_nft_level_view
        getBonusMultiplier => get_bonus_multiplier
        getRarityName => get_rarity_name
        getTotalNftsMinted => get_total_nfts_minted
        getNftTokenId => get_nft_token_id
        getBaseUri => get_base_uri
        getLevelUri => get_level_uri
        getNftUri => get_nft_uri
    )
}

multiversx_sc_wasm_adapter::async_callback! { xcirclex_nft }
