// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    investment_circle
    (
        init => init
        upgrade => upgrade
        setProtocolFee => set_protocol_fee
        withdrawFees => withdraw_fees
        createCircle => create_circle
        joinCircle => join_circle
        startCircle => start_circle
        contribute => contribute
        processMissedContribution => process_missed_contribution
        advancePeriod => advance_period
        claimCollateral => claim_collateral
        leaveCircle => leave_circle
        cancelCircle => cancel_circle
        getCircleInfo => get_circle_info
        getMemberInfo => get_member_info
        getUserCircles => get_user_circles
        getCircleMembers => get_circle_members
        getRequiredCollateral => get_required_collateral
        getPoolBalance => get_pool_balance
        getClaimableCollateral => get_claimable_collateral
        getTotalCircles => get_total_circles
        canStartCircle => can_start_circle
        getPayoutsPerMember => get_payouts_per_member
        canJoinFairly => can_join_fairly
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
