// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           17
// Async Callback (empty):               1
// Total number of exported functions:  20

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_token_protection
    (
        init => init
        upgrade => upgrade
        recordPurchase => record_purchase
        verifyTransfer => verify_transfer
        sellWithTax => sell_with_tax
        setAntiWhaleEnabled => set_anti_whale_enabled
        setSellTaxEnabled => set_sell_tax_enabled
        setMaxWalletPercentage => set_max_wallet_percentage
        setSellTax24h => set_sell_tax_24h
        setSellTax7d => set_sell_tax_7d
        setTreasury => set_treasury
        setExempt => set_exempt
        setAuthorizedRecorder => set_authorized_recorder
        updateTotalSupply => update_total_supply
        getProtectionSettings => get_protection_settings
        getMaxWalletAmount => get_max_wallet_amount
        isExempt => is_exempt_view
        getTrackedBalance => get_tracked_balance
        getSellTaxForUser => get_sell_tax_for_user
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
