// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_staking
    (
        init => init
        upgrade => upgrade
        stake => stake
        claimRewards => claim_rewards
        unstake => unstake
        emergencyUnstake => emergency_unstake
        addRewards => add_rewards
        updateLevelApy => update_level_apy
        setNftContract => set_nft_contract
        getStakePosition => get_stake_position
        getPendingRewards => get_pending_rewards
        getUserPositionCount => get_user_position_count
        getStakingLevel => get_staking_level
        getTotalStaked => get_total_staked
        getRewardsPool => get_rewards_pool
        getTotalRewardsDistributed => get_total_rewards_distributed
        getTokenId => get_token_id
        canUnstake => can_unstake
        getTimeUntilUnlock => get_time_until_unlock
        getEmergencyPenalty => get_emergency_penalty
        getEffectiveApy => get_effective_apy
        getNftBonus => get_nft_bonus_view
        getNftContract => get_nft_contract
        getTotalStakedByUser => get_total_staked_by_user
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
