// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           10
// Async Callback (empty):               1
// Total number of exported functions:  13

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_lp_locker
    (
        init => init
        upgrade => upgrade
        lockLpTokens => lock_lp_tokens
        extendLock => extend_lock
        unlock => unlock
        setMinLockDuration => set_min_lock_duration
        getLockInfo => get_lock_info
        getUserLocks => get_user_locks
        isLockExpired => is_lock_expired
        getRemainingLockTime => get_remaining_lock_time
        getTotalLocked => get_total_locked
        getMinLockDuration => get_min_lock_duration
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
