// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           39
// Async Callback (empty):               1
// Total number of exported functions:  42

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    xcirclex_dao_v2
    (
        init => init
        upgrade => upgrade
        depositToTreasury => deposit_to_treasury
        getTreasuryBalance => get_treasury_balance
        depositEgldToTreasury => deposit_egld_to_treasury
        receiveFromCircleOfLife => receive_from_circle_of_life
        getEgldTreasuryBalance => get_egld_treasury_balance
        createProposal => create_proposal
        vote => vote
        finalizeProposal => finalize_proposal
        executeProposal => execute_proposal
        cancelProposal => cancel_proposal
        vetoProposal => veto_proposal
        councilExecute => council_execute
        setMinProposalThreshold => set_min_proposal_threshold
        setVotingPeriod => set_voting_period
        setTimelockPeriod => set_timelock_period
        setQuorumPercentage => set_quorum_percentage
        setPassThreshold => set_pass_threshold
        emergencyWithdraw => emergency_withdraw
        emergencyWithdrawEgld => emergency_withdraw_egld
        forceExecute => force_execute
        setStakingContract => set_staking_contract
        setCircleOfLifeAddress => set_circle_of_life_address
        getProposal => get_proposal
        getProposalCount => get_proposal_count
        getActiveProposals => get_active_proposals
        getVotingPower => get_voting_power
        getStakingContractAddress => get_staking_contract_address
        getCircleOfLifeAddress => get_circle_of_life_address
        hasVoted => has_voted_view
        getVote => get_vote
        getMinProposalThreshold => get_min_proposal_threshold
        getVotingPeriod => get_voting_period
        getTimelockPeriod => get_timelock_period
        getQuorumPercentage => get_quorum_percentage
        getPassThreshold => get_pass_threshold
        getTokenId => get_token_id
        isCouncilMember => is_council_member
        getCouncilMembers => get_council_members
        getCouncilMemberCount => get_council_member_count
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
